[package]
name = "leanpub"
version = "0.1.0"
authors = ["Patrik Svensson <patrik@patriksvensson.se>"]

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
reqwest = "0.8.6"
serde = "1.0.67"
serde_derive = "1.0.67"
serde_json = "1.0"
