[package]
name = "leanpub"
version = "0.1.0"
authors = ["Patrik Svensson <patrik@patriksvensson.se>"]
description = "Unofficial Leanpub API client."
license = "MIT"

[dependencies]
failure = "0.1.1"
reqwest = "0.8.6"
serde = "1.0.67"
serde_derive = "1.0.67"
serde_json = "1.0"
